### ISSUE TITLE
Error starting up with babel

### ISSUE THREAD

**Issue by 18thletter** [grommet/grommet-native#4]
I just want to point out that to get this fully working, there were a few additional steps I had to do other than the ones listed in the Readme. In addition to doing the react-native getting started steps, I also removed react-native and react as dependendies in my project (since they're already dependencies of grommet-native). After I did an npm install and I linked react-native-svg, I was getting a Babel error like this: Unknown option: foreign.Children. I fixed that by doing an `npm install --save-dev babel-preset-react`. Now everything seems to work fine.

**Comment by tracybarmore** [comment]
Hi 18thletter, We've made some updates to grommet-native over the last few months. Are you still seeing this issue?

**Comment by tracybarmore** [comment]
Hey @18thletter, thanks for all your collaboration with us. We will be cleaning up our backlog last week of Feb 2017 by closing unresponsive issues that haven't been active for at least 30 days.

If you would like this issue to remain open in our backlog, please comment to let us know. Thanks!

**Comment by 18thletter** [comment]
Oops. I'll close! I haven't checked it out recently, as my project has diverged a lot from Grommet Native, but it was a great starting point. Thank you!
